# Generated by Django 5.1.1 on 2024-10-22 01:52

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Danhmuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lienhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('subject', models.CharField(max_length=264)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thuonghieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('image', models.ImageField(default='Store/images/default.png', upload_to='Store/images')),
            ],
        ),
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField(default=0.0)),
                ('price_origin', models.FloatField(null=True)),
                ('image', models.ImageField(default='Store/images/default.png', upload_to='Store/images')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Unisex', 'Unisex')], max_length=50, null=True)),
                ('nam_san_xuat', models.CharField(blank=True, max_length=50, null=True)),
                ('huong_dau', models.CharField(blank=True, max_length=100, null=True)),
                ('huong_giua', models.CharField(blank=True, max_length=100, null=True)),
                ('huong_cuoi', models.CharField(blank=True, max_length=100, null=True)),
                ('nhom_nuoc_hoa', models.CharField(blank=True, max_length=100, null=True)),
                ('phong_cach', models.CharField(blank=True, max_length=100, null=True)),
                ('thoi_gian_luu_huong', models.CharField(blank=True, max_length=50, null=True)),
                ('dung_tich', models.CharField(blank=True, choices=[('30ml', '30ml'), ('50ml', '50ml'), ('100ml', '100ml'), ('125ml', '125ml'), ('150ml', '150ml'), ('200ml', '200ml')], max_length=50, null=True)),
                ('nong_do', models.CharField(blank=True, choices=[('EDT', 'EDT'), ('EDP', 'EDP'), ('Parfum', 'Parfum')], max_length=50, null=True)),
                ('viewed', models.IntegerField(default=0)),
                ('public_day', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.danhmuc')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.thuonghieu')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(default='Store/images/people_default.png', upload_to='Store/images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
